services:
  - type: web
    name: lista-presenca
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
